environments:
  - name: dev
    db_dsn: postgres://user:password@dev-host:5432/database?sslmode=disable
  
  - name: stage
    db_dsn: postgres://user:password@stage-host:5432/database?sslmode=verify-full
  
  - name: prod
    db_dsn: postgres://user:password@prod-host:5432/database?sslmode=verify-full 